export const dogList = [
	{
		id: "#DOG01",
		name: "Mindy",
		breed: "West Highland Terrier",
		speciality: "White and occasionally bites you",
		image: "DOG01",
		amount: 12,
	},
	{
		id: "#DOG02",
		name: "Becky",
		breed: "Irish Wolfhound",
		speciality: "Lone wolf",
		image: "DOG02",
		amount: 10,
	},
	{
		id: "#DOG03",
		name: "Toopac",
		breed: "Great Pyrenees",
		speciality: "Calm but not so calm",
		image: "DOG03",
		amount: 7,
	},
	{
		id: "#DOG04",
		name: "Niles",
		breed: "Irish Setter",
		speciality: "Stylish nonetheless",
		image: "DOG04",
		amount: 5,
	},
	{
		id: "#DOG05",
		name: "Segundo",
		breed: "Australian Kelpie dog",
		speciality: "Pawn to the king",
		image: "DOG05",
		amount: 6,
	},
	{
		id: "#DOG06",
		name: "Kinley",
		breed: "German Shepherd",
		speciality: "One word; loyal",
		image: "DOG06",
		amount: 9,
	},
	{
		id: "#DOG07",
		name: "Donut",
		breed: "Boxer dog",
		speciality: "Cuddler",
		image: "DOG07",
		amount: 11,
	},
	{
		id: "#DOG08",
		name: "Trea",
		breed: "Field Spaniel",
		speciality: "Lowkey philosopher",
		image: "DOG08",
		amount: 10,
	},
	{
		id: "#DOG09",
		name: "Pancho Toast",
		breed: "Chesapeake Bay Retriever",
		speciality: "Part time swimmer",
		image: "DOG09",
		amount: 8,
	},
	{
		id: "#DOG10",
		name: "Bruno",
		breed: "Anatolian Shepherd dog",
		speciality: "Basic and simple",
		image: "DOG10",
		amount: 7,
	},
];
